name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20.17
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node src/app.js
      - run: sleep 10
      - run: pkill -f "node src/app.js"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Running Tests
        run: echo "Testing the code"